# Generated by Django 2.0.13 on 2019-03-09 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ('data',)},
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
